### ISSUE TITLE
Missing wikiwho_pickle?

### ISSUE THREAD

**Issue by jsekamane** [gesiscss/wikiwho_wrapper#3]
I get the following error:

```
>>> from wikiwho_wrapper import WikiWho
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wikiwho_wrapper/__init__.py", line 10, in <module>
    from .pickle_api import WikiWhoPickleAPI
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wikiwho_wrapper/pickle_api.py", line 7, in <module>
    from wikiwho import open_pickle
ModuleNotFoundError: No module named 'wikiwho'
```

I can get it to work, if I replace this line:

https://github.com/gesiscss/wikiwho_wrapper/blob/5390341d6ee8dbdd91168f61a53dfe2cd1d8e9ff/wikiwho_wrapper/pickle_api.py#L7

with these:

https://github.com/gesiscss/wikiwho_pickle/blob/e16e930c2143af195b8344d0affd359bbb5fe2ce/wikiwho/__init__.py#L9-L11

**Comment by postylem** [comment]
I made a pull request to fix this issue.

**Comment by robertour** [comment]
Thank you! An alternative solution would have been to install wikiwho_pickle: `pip install wikiwho-pickle`. It is strange that it didn't install, because it is part of the setup: https://github.com/gesiscss/wikiwho_wrapper/blob/master/setup.py#L34.

I am not sure if there are other dependencies. Otherwise, the current pull (merged) seems the way to go. 

Also, I am not sure how long we will keep the current server. But, Wikimedia foundation now is hosting it: https://wikiwho-api.wmcloud.org/. You would have to modify the hostname of the Wikiwho call accordingly:

https://github.com/gesiscss/wikiwho_wrapper/blob/master/wikiwho_wrapper/wikiwho.py#L19

```
from wikiwho_wrapper import WikiWho
ww = WikiWho(domain="wikiwho-api.wmcloud.org", ...)
```

And they also have added more languages!

**Comment by postylem** [comment]
If maintaining current server is uncertain, and Wikimedia is hosting it now, then for stability going forward, should the default domain be `domain="wikiwho-api.wmcloud.org"`?  I made a PR with just this changed throughout, if that's useful.

https://github.com/gesiscss/wikiwho_wrapper/pull/5
